### ISSUE TITLE
[x] Collection field bug

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#1]
In Drupal we can see a "Collection" field, which we think was originally intended to be a place where institutions could mark which archival collection the item was sourced from--note that it's distinct from the "Collection Guides" field. However, Paula at Radcliffe says that when she adds text to that field (I presume she means in Drupal rather than through a TSV field) nothing shows up. She offers this an example of an item that she knows she added collection info to but where that field is not currently displaying: https://www.collegewomen.org/node/14140  

Can you help us figure out why that field seems to be dormant? We'd like for people to make use of it in conjunction with the Collection Guides field, and to be able to ingest items with Collection information in the TSV as well as being able to add and edit it later in Drupal.

**Comment by jmaj** [comment]
On staging, good to go live if they approve, demo: https://dev-college-women.pantheonsite.io/node/13638
