### ISSUE TITLE
[2] Consolidating “Reset” options on Advanced Search window

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#10]
Currently the Adv. Search window features a “reset” button next to each field. Eliminate, replace with single “reset all” button. 

Rationale: multiple “reset” buttons next to each field are unnecessary (users can easily delete their text input in individual fields) and create visual clutter. Instead, there could be a “reset all” button at the top of the Advanced Search window.

**Comment by jmaj** [comment]
Available for QA on Dev server, https://dev-college-women.pantheonsite.io/browse

**Comment by amberreeves** [comment]
that works

**Comment by jmaj** [comment]
Updated on the live site
