### ISSUE TITLE
[1] Correction to theme titles and standardization of ampersand usage in menu

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#11]
Currently, there is inconsistency in ampersand and oxford comma usage. We would like to standardize so that all themes use “and” instead of “&” and none use an oxford comma. 

Two themes use the word “and”--“Political and Social Activism” and “Arts, Theater, and Music” while the rest do not. We would like to amend the following themes: “Athletics (& → and) Physical Education,” “Buildings (& → and) Grounds,” “Home (& → and) Family,” “Religion (& → and) Spirituality."

Other changes to themes include: 

- “Arts, Theater, and Music”: removing the oxford comma so that the new theme reads “Arts, Theater and Music”
- “Faculty, Staff, Administrators”: removing the oxford comma and adding “and” so that the new theme reads “Faculty, Staff, and Administrators.”
- “Tradition”: changing theme title to “Tradition and Ritual”

Rationale: consistency of usage, title of “Traditions & Ritual” theme better covers the content of the theme.
Note: these changes should be reflected in both the Themes menu on the site and in our TSV ingest rules.

**Comment by jmaj** [comment]
What is or where are the TSV ingest rules?

**Comment by mtedeschi** [comment]
I think we can just adjust the themes menu—the TSV ingesting should still work as long as they're consistent (that's on them).

**Comment by jmaj** [comment]
Alright, updated on the live site and the cache has been cleared

**Comment by amberreeves** [comment]
OK these all look good. There is one error though that the client made in the instructions. 

“Faculty, Staff, Administrators”: removing the oxford comma and adding “and” so that the new theme reads “Faculty, Staff, and Administrators.”

This does not remove the oxford comma. It should be: 

Faculty, Staff and Administrators

@jmaj can you make this edit?

**Comment by jmaj** [comment]
Alright, updated

**Comment by amberreeves** [comment]
looks good
