### ISSUE TITLE
[x] Description text display issue

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#12]
The text in the description field cuts off in odd places. Sometimes certain lines are shorter than others, like in this item: https://www.collegewomen.org/node/13533
 
In other cases, things actually cut off mid-word, as in "mineral" here: https://www.collegewomen.org/node/13578
 
I don't see anything odd in the TSV we used to upload those items in 2015. Do you know why it might be happening?

**Comment by mtedeschi** [comment]
So, there are nonbreaking spaces between all/most of the words, which is leading to long words that run over the container. To fix that, it has css word-break on it so it doesnt' look horrible, but it causes this weird cutting problem.

We'll have to find a way to remove those nbsp from the outputted text to solve this and remove that css word break.

**Comment by jmaj** [comment]
Available for QA on the dev server, https://dev-college-women.pantheonsite.io/node/13578

**Comment by amberreeves** [comment]
looks good

**Comment by jmaj** [comment]
Updated on the live site, ready to be checked
