### ISSUE TITLE
[1] Images not appearing in blog posts

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#13]
From Evan
You can see my unpublished draft in Drupal now under "The Radicalization of Mary Whitall Worthington". The first image is towards the top of the post and is centered. The second one was supposed to be aligned to the right towards the bottom of the post, but it isn't appearing at all (if you have a look here: https://www.collegewomen.org/node/14504), though it is still included in the draft if you go to edit the post. Can you help me figure out why the image isn't appearing?

Update from Evan
I noticed that [the most recent blog post from Wellesley](https://www.collegewomen.org/node/14617) contains multiple images, which I wasn't able to do last time I tried to upload a post of my own. I'm not sure if that means you have already fixed that bug?

**Comment by mtedeschi** [comment]
I am unable to recreate this issue. Tried in the post Evan called out, and in other posts, and have no problem at all with multiple images (especially since they removed the image in question).

**Comment by amberreeves** [comment]
ok i'll let evan know.
