### ISSUE TITLE
[2] Blog post update error

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#15]
From Evan

I Just tried to edit the two most recent posts to include bylines (Mount Holyoke College for the most recent and Smith College for the one before that). Both times I went to edit the post, added the byline, and clicked save, and got this error message:

[{"command":"settings","settings":{"basePath":"\/","pathPrefix":"","ajaxPageState":{"theme":"sisters","theme_token":"z8xB_HZVdhPu-dssVvfp2NxpNKOG41cfAE7oX7XzHNs"}},"merge":true}]

Update from Evan
Actually, it looks like the update did take effect and the bylines now appear. I guess it wasn't an error message after all, but just code. Can we fix it so that that doesn't appear, and the user is instead rerouted to the Find Content page?

**Comment by amberreeves** [comment]
@jmaj - For the posts, I haven't find a proper solution for it. I've found and tried stuff online but no luck. I will talk it further with mike because we're using pantheon, we don't have access to the core files like we normally would

**Comment by mtedeschi** [comment]
Looked into this further. Appears to be an error from the Views Ajax module (https://www.drupal.org/node/1036962#comment-6665274) when you follow the steps outlined there (filter the admin/content view, edit a post, save it).

Will push the patch live with latest updates to test it.

**Comment by amberreeves** [comment]
Did this get pushed live with the drupal module?
