### ISSUE TITLE
[1.5] Blog images with captions should align left/right/center

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#16]
Right now, there isn’t a good way that we’re handling captions (I came up with a kind of crappy way to do it using the sup tag and some ghetto javascript). We should replace it with a module like this and style it to match:
https://www.drupal.org/project/ckeditor_image2

From Evan:
“I was also having trouble getting the superscript to align with the bottom of the (second, right-aligned) image since it’s just free-floating text and isn’t actually associated with the image. I couldn’t tell where the image was going to appear given the differences in line length between the way the text appears in the draft versus on the site. Is that something that the caption module, which you mention below, would fix?”

**Comment by mtedeschi** [comment]
I've installed a new module that makes all of this easier (captions are all built in, much cleaner). Here is an example: https://dev-college-women.pantheonsite.io/node/13005

**Comment by amberreeves** [comment]
From Evan

I definitely like the look of the captions and image formatting on the blog. I passed it along to the Content Committee so that I can get feedback from a few other people, and I gave them until Tuesday to send comments.

One thing that would be nice is if the image placement was reflected in the "preview" feature. When I click to preview the post, it always shows the image centered above the text whether or not I've selected that option or chosen to push it to the left or the right. It would be nice if Preview allowed the user to see how the image placement will look once published.

**Comment by mtedeschi** [comment]
I'm not sure I'll be able to add anything to make the preview image look the way she wants. I'm also not sure I see what she's seeing. Here is what I see when I preview with caption:

<img width="1618" alt="screen shot 2017-08-02 at 9 29 49 pm" src="https://user-images.githubusercontent.com/842387/28901948-c9e71f1e-77c9-11e7-8a18-f4fbd7a77ac5.png">

**Comment by amberreeves** [comment]
sent to evan

**Comment by mtedeschi** [comment]
The committee approves the image caption feature! Please feel free to move it to the live site.

**Comment by amberreeves** [comment]
Did this get pushed live with the drupal module?

**Comment by mtedeschi** [comment]
Drupal module isn't pushed live—it's on dev until they approve it, or we can just push it up while they test and not use it on production till its approved.
