### ISSUE TITLE
[2-4] Push Drupal Feeds importer to Pantheon dev site

### ISSUE THREAD

**Issue by mtedeschi** [InteractiveMechanics/CollegeWomen_Drupal7#17]
We got a response from BMC folks on our questions. The full email is at the bottom, but I pulled out the key things for you here:

We're dropping <dcterms:temporal>start=XXXX; end=XXXX;</dcterms:temporal> and instead will have <startdate> and <enddate>. We can update the importer to reflect that.

Any duplicate tags just show the same data, so we can ignore them and let the module do what it already does (which is take the last one).

Endpoint for testing:
http://54.214.112.66/repox/OAIHandler?verb=ListRecords&metadataPrefix=oai_dc&set=Barnard_photographs

-----

From Martha:
"1. There is one adjustment we need to make: the way things are set up, the tamper piece isn’t functioning, and in favor of not wasting time on it, we’d like to suggest that we change 
<dcterms:temporal>start=XXXX; end=XXXX;</dcterms:temporal> 
to something else, like two different fields with the start and end values:  
<dcterms:startyear> and <dcterms:endyear>

Sure, I can update this on our documentation and in my XSLT. I think I will change it to  <startdate> and <enddate> to make it more consistent with the field for the TSVs unless someone has a different suggestion; there's no field in DC called "startyear" anyway. I think it would be good to alert the metadata working group to this change, too, though it won't affect anyone currently working on TSV ingest. A note--I did update this.

2. We also have a general question about what data from REPOX we should set up to be imported, and what we should do with the existing data/records in Drupal. Do you want to keep the ~300 or so records that are in there still and import in addition to those?

As far as I know, they shouldn't touch the existing records in Drupal, since those are all from institutions that aren't doing a REPOX ingest (so there won't be any overlap). I've deleted Barnard's existing ~20 records because we've changed the identifiers that we're ingesting and as such the REPOX ingest would create duplicate records. But in the future we'll just do REPOX re-ingests and update/add to existing records.

3. Also, we’re still seeing duplicate tags, like multiple <dc:format> and others. We were under the impression this was resolved. Can you check in on that?

The duplicate format tags don't pose a problem for Barnard, since they are all exact duplicates (I think they're all multiples of <dc:format>Photographs</dc:format> as a result of mapping multiple AAT terms to our limited CW set). So it's not an issue if those fields are overwritten/only one is actually ingested since they are all the same. If the multiple tags are going to trip the module up, let me know and I can try to adjust the XSLT. "

**Comment by amberreeves** [comment]
@jmaj will create an importer so the client can use it.

**Comment by jmaj** [comment]
I will set this in place and we can email them Aug 1st. I've deleted the old importers and added another one but it's reference thing the old module still. 

- So I will have to make another commit which removes the old module. 
- Add back the new module
- Clear cache
- Install Module
- Then add the importer back so Drupal is referencing the new Module

**Comment by amberreeves** [comment]
@mtedeschi when jeff is ready tomorrow (tuesday aug 1), can you take a look at this and let me know if there is anything i need to include to send it to evan and martha?

**Comment by jmaj** [comment]
I spoke with Pantheon.io support today. They are going to clear their cache, so I know for sure that module is gone. We have a support ticket with them the case number is 87331.

Once they've cleared the cache, I will be able to commit the new module.

**Comment by amberreeves** [comment]
Pantheon delivered instructions for next steps that Jeff will follow today.

**Comment by jmaj** [comment]
I've been talking to pantheon since the morning, will keep you guys updated.

**Comment by jmaj** [comment]
There's a back and forth with me.and support. I'm pausing this to work on PMA

**Comment by amberreeves** [comment]
From Mike - While attempting to push the module changes from local development to Pantheon’s dev site, we noticed that our changes weren’t taking effect. We attempted a number of things (including completely removing the modules and readding it with our changes, and creating a brand-new version of the module), but Pantheon still is not recognizing the new module. We’ve communicated with Pantheon support to help us get this resolved, but the recommendations would require a considerable amount of time. Until we get that resolved, we cannot further test the ingestion on the site or push new changes to the live site.

**Comment by mtedeschi** [comment]
@jmaj can you push the latest OAI Feeds code up (make sure to pull down the latest). I've gone through and changed the database tables and settings.php file as they requested. I want to see if this now works.

**Comment by jmaj** [comment]
I removed the copy of the module and commit the code but it's still showing up. Earlier I mentioned that I think that the module is being pulled from the live environment that still seems to be the case here. 

Mike if you pull down a copy of dev and look at the module folder, you'll find no reference in the OAI module. But if you go here,  https://dev-college-women.pantheonsite.io/admin/modules you'll see that the OAI Module is still there and can be turned on. So it's pulling it from one of the environments.

**Comment by amberreeves** [comment]
@jmaj - i removed the copy of the module and commit the code but it's still showing up. Earlier I mentioned that I think that the module is being pulled from the live environment that still seems to be the case here.

Mike if you pull down a copy of dev and look at the module folder, you'll find no reference in the OAI module. But if you go here,  https://dev-college-women.pantheonsite.io/admin/modules you'll see that the OAI Module is still there and can be turned on. So it's pulling it from one of the environments.

mike - okay, so the solution pantheon proposed didn’t resolve it

**Comment by amberreeves** [comment]
Mike downloaded and installed Terminus to run drush commands and rebuilt the registry, cleared all cache, and also found what might have been a duplicate of the module hiding that could have been conflicting. If we can attempt to push that up now, it might work.

**Comment by mtedeschi** [comment]
This is done now, just diagnosing why the import isn't working in a separate issue.
