### ISSUE TITLE
[2] Add Twitter and Facebook icons to home page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#18]
Add Twitter and Facebook icons to the home page with links to the College Women History social media accounts (@CollegeWmnHist).

**Comment by amberreeves** [comment]
This has been approved by the client

**Comment by mtedeschi** [comment]
Added to the footer:
https://dev-college-women.pantheonsite.io/

**Comment by amberreeves** [comment]
i'll pass this to evan for review/approval

**Comment by amberreeves** [comment]
From Evan
All of us like the way the icons look at the bottom of the page, but thought they were too out of the way--not likely to be seen by someone unless they were looking specifically for our social. Would it be possible to incorporate it into the top header? If we can only pick one, I'd prefer to see them on the top menu (or elsewhere if you can think of a better location that's still somewhere above the bottom border of the background image) but I wouldn't mind having them in both places. What do you think?

**Comment by mtedeschi** [comment]
Here's an alternative idea: what if we add them as blue circles with white icons floating in the bottom right corner of the screen near the "FEEDBACK" button? Then we don't need to try to find a way to make them work in the main navigation, and they're still available all the time (and on all pages).

**Comment by amberreeves** [comment]
sent to evan

**Comment by mtedeschi** [comment]
I think your idea for the social icons is ideal, and very creative. Let's try that!

**Comment by mtedeschi** [comment]
Implemented, here:
https://dev-college-women.pantheonsite.io/

**Comment by amberreeves** [comment]
sent to evan for review

**Comment by amberreeves** [comment]
this was pushed live with the latest changes
