### ISSUE TITLE
[x] Blog: Image caption displaying in the wrong place

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#19]
On the Mary Whitall Worthington blog post, Evan added a caption to the first image in the body but did not add a caption to the second image.

When she published the updated post, both the first and second images include the caption she added to the first image and with the second image, the caption text is on top of the text of the article. 

If this is related to the other captioning issues and will be resolved once we push that fix live, we can close this issue. 

Blog post
https://www.collegewomen.org/node/14504

![caption issue](https://user-images.githubusercontent.com/20477677/29029812-e92aab30-7b56-11e7-96dc-196806117f4d.png)

**Comment by mtedeschi** [comment]
We redid the captioning system, not yet pushed live till we get the module issues with Pantheon resolved. This is likely a non-issue since none of this gets used after that.
