### ISSUE TITLE
[0.5] Install Porter Stemmer module on the dev site. 

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#21]
Install Porter Stemmer module on the dev site. The client would like to experiment with search stemming using this module before deciding whether they want to use it on the live site.

https://www.drupal.org/project/porterstemmer

**Comment by mtedeschi** [comment]
Installed on dev and ran site reindexing for them to test.

**Comment by amberreeves** [comment]
this was pushed live with the latest changes
