### ISSUE TITLE
[0.25] 1b: Change Browsing # Items text on Explore Collections page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#28]
On the Explore Collections page, change the "Browsing XXXX Items" text to "Viewing all XXXX items" or "Viewing XXXX items [All]"
To make it clear when user is viewing all items on site vs. a limited selection.

https://www.collegewomen.org/browse

![browse open access portal](https://user-images.githubusercontent.com/20477677/34014017-aaa22194-e0e7-11e7-9153-3df0d88368e5.png)

**Comment by mtedeschi** [comment]
Just to be clear, all this task needs is to check if its the full results and add "[All]" to the end of the string from #29.

**Comment by mtedeschi** [comment]
One approach for how to do this is to check the URL path for a query string. If it shows a query string (e.g. there are filters applied) then show the "X items found" message, otherwise show "Viewing all XXXX items".

**Comment by amberreeves** [comment]
i'm not seeing the [All] here. @mtedeschi can you confirm?

**Comment by mtedeschi** [comment]
This is complete.
