### ISSUE TITLE
[0.5] 1c: Change Browsing X Items text on search results page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#29]
On a search results page, change the Browsing X Items text to "X items found"

Example search results page: 
https://www.collegewomen.org/browse?searchterm=&start_year=&end_year=&subject=&type=Black-and-white%20photograph&institution=

![browse open access portal 1](https://user-images.githubusercontent.com/20477677/34014136-1314a864-e0e8-11e7-9a4b-0b2b9f0ea0e8.png)

**Comment by amberreeves** [comment]
looks good. 

https://bmc-d7-college-women.pantheonsite.io/browse?searchterm=sports

![browse open access portal 3](https://user-images.githubusercontent.com/20477677/35828249-d4e4bc40-0a8c-11e8-925f-aeb8a07b8afb.png)

**Comment by mtedeschi** [comment]
This is done. It should only show "Viewing all..." when all results in the set are returned.
