### ISSUE TITLE
[0.25] Outgoing links open in new window

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#3]
On item page, when clicking on the item image or the “view original item” link, target link to open in new window/tab.

Rationale: users have given feedback that it’s confusing to be directed away from College Women to institutional repositories when clicking on an item, and the current arrangement doesn’t offer a way to easily get back to the site. This would be a simple way to make sure they can return to College Women.

**Comment by jmaj** [comment]
Is this only for the browse items content type. Or does it apply site wide with all outgoing links?

**Comment by mtedeschi** [comment]
I think its just for the browse items content pages.

**Comment by jmaj** [comment]
Available for QA on Dev server, https://dev-college-women.pantheonsite.io/browse

**Comment by amberreeves** [comment]
if i understand this correctly, 

when i go here https://dev-college-women.pantheonsite.io/browse, click on an item, then click on both the image itself and the 'view original' link at the bottom of the page, the next page should open up in a new window. 

right now, it is opening in the same window.

if i'm missing something or looking at the wrong thing, let me know.

**Comment by amberreeves** [comment]
this is another instance where the client's request is contradicting itself. @mtedeschi she says in the first sentence clicking on an image should 'open in a new window' (which the site currently does), then the rationale says 'it’s confusing to be directed away from College Women to institutional repositories when clicking on an item', suggesting she wants it to open in the same window. any context/thoughts on what she wants here?

**Comment by amberreeves** [comment]
From Evan

I think this item can be removed. the user was expressing confusion that clicking on the item took them away from College Women without an easy link back, and we came up with was to have the local repositories open in a new tab--but the site already does this! I had thought I edited/removed this item from the list.
