### ISSUE TITLE
[0.5] 2: Make Advanced Search more prominent on Explore Collections page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#31]
Make the link to the Advanced Search window (currently the Search link) on Explore Collections page more prominent.

https://www.collegewomen.org/browse

![browse open access portal 5](https://user-images.githubusercontent.com/20477677/34014479-3c7a5ad6-e0e9-11e7-8c6b-1f9f32f99c74.png)

@mtedeschi to provide design

**Comment by amberreeves** [comment]
Evan has one question:

Joanna and I have been talking about whether the "Advanced Search" button/window should just be called/labeled "Search." I had thought it made sense to keep the "Advanced Search" language to draw a distinction with the basic keyword search option on the homepage, but that may not be as confusing to users as I imagined. And it might be clearer to call the search window "Search." Do you have an opinion on that?

**Comment by mtedeschi** [comment]
Just "Search" is good with me.

I'm open to @tespenshade's thoughts on how to make it stand out more. Wrapping it in a border like the buttons next to it is one idea, but may be too chunky.

**Comment by tespenshade** [comment]
Re: Making search btn stand out more. I was expecting it to have the same functionality as "Themes" when I first clicked it, so one thought I had was putting the magnifying glass icon in place of the arrow. Magnifying glass icon could be blue, or treated similarly to the sorting buttons next to it.

Another thought was changing the text color to the accent blue, but worry there's a risk of it being confused with a link. Could also just **BOLD** it.

Last thought was adding a highlight color behind the text (a light gray maybe?) but that feels as chunky as treating it like a button.

**Comment by amberreeves** [comment]
Evan has opted for just the word 'Search' for the link in the header. 

She would like it styled like a button, like the ones to the right of it.

**Comment by tespenshade** [comment]
Img of revised search button treatment attached and on drive [here](https://drive.google.com/open?id=1OUblDErcUojGQv6dA_mhzAUzMLSt47W8)

![2018_01_19_collegewomen_phaseiiidesigns_v01_search](https://user-images.githubusercontent.com/20828448/35159562-9da83cfc-fd08-11e7-92b7-e8cf1a5898bf.jpg)

**Comment by amberreeves** [comment]
@cworthen this button design for the Search link has been approved by the client.

**Comment by amberreeves** [comment]
looks good to me. @mtedeschi can you confirm?

https://bmc-d7-college-women.pantheonsite.io/browse?searchterm=sports

![browse open access portal 2](https://user-images.githubusercontent.com/20477677/35828213-b18eedb0-0a8c-11e8-808a-a8057aaf6503.png)

**Comment by mtedeschi** [comment]
Looks good!

**Comment by amberreeves** [comment]
Evan has asked that we change the label on this search button back to Advanced Search.

![browse open access portal 2](https://user-images.githubusercontent.com/20477677/36983155-a661ffe8-205f-11e8-892b-bf742134ec9d.png)

**Comment by amberreeves** [comment]
looks good
