### ISSUE TITLE
[0.5] 3a: Remove Subjects field from Advanced Search

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#32]
Remove Subjects field from Advanced Search window.

![browse open access portal 6](https://user-images.githubusercontent.com/20477677/34014521-6e70f0d6-e0e9-11e7-8d73-29d3c7b5e279.png)

**Comment by cworthen** [comment]
removing subjects from advanced search, once subjects is removed -- search results no longer appear. @mtedeschi

**Comment by mtedeschi** [comment]
@cworthen: we might just need to leave the ?subject= part of the querystring blank to return all results. Which might mean just hiding that item from the search instead of removing it entirely.

**Comment by mtedeschi** [comment]
@cworthen: this isn't working properly—&subject= is getting "undefined" in the search which does not return results. You'll want to just have it return blank or remove &subject= entirely.

**Comment by amberreeves** [comment]
subject field is not longer appearing in the search window. @mtedeschi can you confirm?

**Comment by mtedeschi** [comment]
Confirmed.
