### ISSUE TITLE
[0.5] 3d: Remove some format types from Advanced Search

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#35]
In the Advanced Search window, remove all Format types from dropdown menu **except**: 

1. Diaries
2. Correspondence
3. Photograph albums
4. Photographs
5. Scrapbooks

![screen shot 2017-12-14 at 4 17 10 pm](https://user-images.githubusercontent.com/20477677/34014737-45be6618-e0ea-11e7-89c1-e9eb68c98e85.png)

**Comment by amberreeves** [comment]
looks good

https://bmc-d7-college-women.pantheonsite.io/

![screen shot 2018-02-05 at 3 50 13 pm](https://user-images.githubusercontent.com/20477677/35828091-54b349b0-0a8c-11e8-8b3d-1c25a32e0eba.png)

**Comment by amberreeves** [comment]
i'm still seeing all the old formats in the advanced search drop down

![screen shot 2018-03-09 at 2 29 24 pm](https://user-images.githubusercontent.com/20477677/37225944-534d3530-23a6-11e8-91b1-b87ea1384af4.png)

**Comment by amberreeves** [comment]
we're waiting until monday to see if this updates when the Drupal 12 hour cache lifespan passes.

**Comment by cworthen** [comment]
Hey @amberreeves @mtedeschi, I looked more into this and found a solution. I don't it kept showing old formats in drop down but I added a line of css to show only the first six formats:
 `.itemtype-filter option:nth-of-type(1n+7){
    display:none;
  }`

Luckily, this did the trick.

**Comment by mtedeschi** [comment]
Looks good!
