### ISSUE TITLE
[6] 4: Show filters applied on search results page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#36]
Show filters applied on search results page give and allow the user to  remove them one-by-one (triggering page refresh each time).

@mtedeschi to provide design

**Comment by amberreeves** [comment]
@cworthen see design and annotations

https://marvelapp.com/2h8b1hj/screen/37146139

**Comment by cworthen** [comment]
For the little ‘x’ in a circle icon next to the filter, are there images of the ‘x’ icon you would like me to use or can I use font awesome to add the icon  ?

**Comment by mtedeschi** [comment]
@cworthen you can use font-awesome, that's fine! If you'd prefer that I give you an image asset, just let me know and I can export that for you.

**Comment by amberreeves** [comment]
@mtedeschi can you take a look?

**Comment by mtedeschi** [comment]
This is nearly done.

**Comment by mtedeschi** [comment]
Okay, done.
