### ISSUE TITLE
[1] 6b: Add Themes field to search results

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#38]
Replace the Subjects field on the search results page with a Themes field.

**Comment by cworthen** [comment]
@mike  Unfortunately I'm still blocked on getting the themes to populate in the search results, I tried editing the view, which works like it should but will not reflect on the front page.

**Comment by amberreeves** [comment]
@mtedeschi can you take a look?

themes are not populating on the search results page

https://bmc-d7-college-women.pantheonsite.io/browse

**Comment by mtedeschi** [comment]
Getting the links to populate, but need to get theme names to appear. Pausing for now.

**Comment by mtedeschi** [comment]
Added in.

**Comment by amberreeves** [comment]
@mtedeschi i'm still not seeing themes in the themes column on the search results page. do these items just not have themes assigned to them yet, or does this need more work? i've cleared the cache in drupal.

example
https://bmc-d7-college-women.pantheonsite.io/browse?subject=&institution=All&start_year=&end_year=&title=&searchterm=art&type=&theme_id=All&sort_by=title&sort_order=ASC

**Comment by amberreeves** [comment]
evermind, wrong branch
