### ISSUE TITLE
[1] 6c: Add excerpt field to search results

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#39]
On the search results page, add a column for an excerpt of the item description (with a character limit).

@mtedeschi to provide design

**Comment by amberreeves** [comment]
@cworthen see design and annotations

https://marvelapp.com/2h8b1hj/screen/37146139

**Comment by amberreeves** [comment]
i'm not seeing the excerpt field. @mtedeschi can you double check this one?

https://bmc-d7-college-women.pantheonsite.io/browse?searchterm=sports

![browse open access portal 1](https://user-images.githubusercontent.com/20477677/35828037-2100988e-0a8c-11e8-802b-b77007419355.png)

**Comment by cworthen** [comment]
@amberreeves for the excerpt field, you have to manually add it in,  just like the other content such as description, collection, etc. 
![screen shot 2018-02-05 at 5 19 23 pm](https://user-images.githubusercontent.com/16109830/35831738-c4f5c084-0a98-11e8-87e4-e3209e8a6a23.png)

I only added one as an example. You can find by hitting enter on the homepage, it should be the first item on the list. 
 
![screen shot 2018-01-21 at 9 22 45 pm](https://user-images.githubusercontent.com/16109830/35832002-a2d0f18a-0a99-11e8-8138-1fe101e53965.png)

**Comment by amberreeves** [comment]
@mtedeschi this looks good to me. can you confirm?

**Comment by mtedeschi** [comment]
Looks good. Stripped extra p tags out so they don't conflict with styling.
