### ISSUE TITLE
[6] Searching by item format

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#4]
Ability to filter by format type in advanced search window with drop-down or checkboxes rather than text field. 

Rationale: users in Phase I user testing were interested in being able to navigate more easily based on format; we expect this to be a key wish for users who want to browse based on the type of item in addition to content-related tags. Current text field was built because of lack of controlled format vocabulary in Phase I items (too many irregular terms to fit in a dropdown/checkbox menu); new standards developed by the metadata committee narrow it down to a small and more manageable list.

**Comment by jmaj** [comment]
I'm not sure about this Estimate.

**Comment by mtedeschi** [comment]
What would you estimate it as?

We should be taking what we currently have as an autocomplete and replacing with a dropdown.

**Comment by jmaj** [comment]
Changed to dropdown, QA here, http://staging.interactivemechanics.com/7sisters/

**Comment by amberreeves** [comment]
looks good to me

**Comment by jmaj** [comment]
Up on the live site

**Comment by amberreeves** [comment]
@jmaj can you take a look at the format drop down in the advanced search window and confirm that the format options are correct? i see duplicates and a gap between options. is that a bug we can fix or is that an issue with how the client entered the format options?

![screen shot 2017-06-16 at 4 13 56 pm](https://user-images.githubusercontent.com/20477677/27243263-125de65a-52af-11e7-94a4-86c1792532a8.png)

**Comment by jmaj** [comment]
It's not a bug, it's how the data is. 

There was probably an item in the feed that was all lowercase so that value is no in the database. So it will get pulled as a Format.

**Comment by amberreeves** [comment]
gotcha. thanks.
