### ISSUE TITLE
[1] 7e: Link Themes on item pages

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#40]
Link Themes on item pages so that they link to the search results page for that theme.

Example item page
https://www.collegewomen.org/node/14207

![letter from ruby willis wellesley massachusetts to dr and mrs william h willis reading massachusetts 1905 october 22 open access portal](https://user-images.githubusercontent.com/20477677/34015106-74262c88-e0eb-11e7-81c0-85c0f70591ab.png)

**Comment by cworthen** [comment]
I'm blocked on getting the theme listed on the item page to be linked to the search results for that theme.

**Comment by mtedeschi** [comment]
@cworthen: where/what are you stuck on (I can help a bit more if you describe what's not working)?

What you'll likely want to do is follow how we structured things for the subject links where it builds a URL like this: https://www.collegewomen.org/browse?theme_id=###

The ### is the id of the taxonomy term.

**Comment by mtedeschi** [comment]
Use the same thing as subjects above:

```
<?php if($node->field_subject['und'][0]['value']): ?>
                                        	<div class="content-detail">
                                            	<span class="heading">Subject</span>
                        	
                                            	<?php
                                            		$subjects = $node->field_subject['und'];
                                            		$subjects_str = "";
                        							foreach($subjects as $item) {
                        	                                    			if($item) {
                        														$subjects_str .= '<p><a href="' . $base_path . 'browse?subject=' . trim($item['value']) . '">'. $item['value'] .'</a></p>';
                        													}
                                                            			}
                                            	?>
												<p><a href="#"><?php print $subjects_str;?></a></p>
											</div>
										<?php endif ?>
```

**Comment by cworthen** [comment]
@mtedeschi @amberreeves I tried this code and it linked the themes names but its not going to the correct destination, instead its going to a blank page. I also tried other methods and I'm having difficultly getting the themes to link to the node pages.

**Comment by cworthen** [comment]
@mike @amberreeves I tried this code and other methods, and still having blockers linking the theme name to the right location/node page. It appears to be linked but it goes to a blank page.

**Comment by amberreeves** [comment]
@mtedeschi can you take a look?

**Comment by mtedeschi** [comment]
Fixed.

**Comment by amberreeves** [comment]
the themes links are still going to 404 pages. 

one example, if you click Athletics & Physical Education on this page
https://bmc-d7-college-women.pantheonsite.io/node/14061

you get this page
https://bmc-d7-college-women.pantheonsite.io/taxonomy/term/

**Comment by amberreeves** [comment]
nevermind, wrong branch

**Comment by mtedeschi** [comment]
One thing I found was that we need to implement the addition of the "?searchterm=" querystring to this and subjects so we have the proper "X items found" message appearing.

**Comment by amberreeves** [comment]
@mtedeschi can you confirm this one?

**Comment by mtedeschi** [comment]
Good!
