### ISSUE TITLE
[0.5] 8b: All Institutions boxes checked in Advanced Search

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#41]
In the Advanced Search window, all of the Institutions check boxes should be checked by default.

**Comment by amberreeves** [comment]
From Evan
Before you begin implementing the requested changes to the (Advanced) Search window itself, we've also been floating different ideas for how the Institution checkboxes might work. In the dev list we suggested adding a check/uncheck all box and having it checked by default; Joanna suggested simply adding text (hover text, or permanently displayed on window?) that says something like, "Limit your results to certain institutions, or leave blank to search all." Do you have an instinct for which would be better? Her idea does seem simpler and maybe more elegant.

**Comment by tespenshade** [comment]
Imagining that consistency throughout the search box is helpful- maybe a "Select All" option next to "THEMES" and "INSTITUTIONS" makes the most sense. As to leaving it checked by default or not is something user testing could help with, if they want to see what users are doing most.
Copying @mtedeschi just to keep track of my suggestions vs. his

**Comment by mtedeschi** [comment]
Second @tespenshade's comment. I'd lean towards "Select All / None" as text links, instead of a description as Joanna suggested.

My suggestion for having them all checked by default is that they are all search for by default, so it matches the behavior of the search. That said, the above solution could avoid needing to do that.

**Comment by amberreeves** [comment]
@mtedeschi can you respond to this?

me: Advanced search Institution checkbox functionality: We suggested adding "Select All / Select None" as text links next to "Themes" and "Institutions", so the checkboxes will not be checked by default, the user will select one of these options. 

evan: This makes visual sense, but it may not do enough to reduce confusion (which already exists) about what it means to run a search with no boxes checked. Will that search still return results from all institutions? Will there be any way of indicating that to the user?

**Comment by tespenshade** [comment]
Img of revised "search all" results treatment attached and on drive [here](https://drive.google.com/open?id=1OUblDErcUojGQv6dA_mhzAUzMLSt47W8)

Searching with all boxes checked or unchecked returns results from all institutions and this is shown in the header (next to themes) as "Institutions: All"

Searching within three or less institutions shows the names of the selected institutions. Searching within 4+ institutions shows number of selected institutions, unless all are selected, which then shows "Institutions: All"

![2018_01_19_collegewomen_phaseiiidesigns_v01_search-5](https://user-images.githubusercontent.com/20828448/35160372-f0a096a0-fd0a-11e7-9bf8-b21663e7e9a2.jpg)
![2018_01_19_collegewomen_phaseiiidesigns_v01_search-all](https://user-images.githubusercontent.com/20828448/35160373-f0ab629c-fd0a-11e7-81fa-dcd84d485642.jpg)
![2018_01_19_collegewomen_phaseiiidesigns_v01_search](https://user-images.githubusercontent.com/20828448/35160374-f0b98340-fd0a-11e7-8f44-628223998284.jpg)

**Comment by amberreeves** [comment]
@cworthen the designs and the following functionality have been approved by the client:

Searching with all boxes checked or unchecked returns results from all institutions and this is shown in the header (next to themes) as "Institutions: All". Searching within three or less institutions shows the names of the selected institutions. Searching within 4+ institutions shows number of selected institutions, unless all are selected, which then shows "Institutions: All".

**Comment by cworthen** [comment]
@mtedeschi 90% of this task is completed, I hit a blocker with remove the 'x' icon and removing theme from search results prompting a page refresh

**Comment by cworthen** [comment]
@mtedeschi @amberreeves  I think is completed, please let me know if there's anything I overlooked or if something needs to be tweaked. Thank you!

**Comment by amberreeves** [comment]
@mtedeschi i see the functionality as described by the client is working here
https://bmc-d7-college-women.pantheonsite.io/

Searching with all boxes checked or unchecked returns results from all institutions and this is shown in the header (next to themes) as "Institutions: All". 
Searching within three or less institutions shows the names of the selected institutions. 
Searching within 4+ institutions shows number of selected institutions, unless all are selected, which then shows "Institutions: All".

it looks like all Themes are selected by default here as well. that was not included in the client's original request, but was suggested by tara for consistency in the search box. @mtedeschi can you make a call on this, or would you like me to pass it back to the client?

**Comment by mtedeschi** [comment]
I like the consistency. Going to flag as good to go.
