### ISSUE TITLE
[24] 13: Data export feature

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#42]
Our suggestion: 

Select the range of a data set
Run a faceted search, results page would have export button
All data from your search returned (or, if all results, export everything)
Formats for export: JSON, CSV, TXT

We said we can come up with a streamlined version of the option we originally suggested. We can install the module and set it up at a basic level. Instead of allowing the user to select a subset of data, they'd download everything. We could then add on specific exporting features in the future if you want. 

@mtedeschi can you revise this description to include what Candace will need to create this feature the way you envision it?

**Comment by mtedeschi** [comment]
https://www.drupal.org/project/views_data_export

**Comment by amberreeves** [comment]
@cworthen i see the csv button that exports the search data at the bottom of the page here. this is supposed to say Export and there should be options for csv, txt, and json. 

@mtedeschi can you give some direction on this, and on the placement and design of the button?

https://bmc-d7-college-women.pantheonsite.io/browse

![browse open access portal 4](https://user-images.githubusercontent.com/20477677/35828627-3e9824f0-0a8e-11e8-806d-bcc2051e266b.png)

**Comment by mtedeschi** [comment]
@cworthen, @amberreeves: apologies, I didn't give you a design for this. If we can just have those labels displayed as you have them here, centered, with a bit of padding above/below, that should work.

Ideally we can have an icon for CSV, JSON, TXT downloads.

**Comment by amberreeves** [comment]
@mtedeschi can you confirm this is what you're thinking for this?

https://bmc-d7-college-women.pantheonsite.io/browse?searchterm=sports&start_year=&end_year=&type=&institution=All&theme_id=All

![browse open access portal 2](https://user-images.githubusercontent.com/20477677/36384539-a0173dae-155d-11e8-99bb-5cab10cb0baa.png)

**Comment by mtedeschi** [comment]
Files are returning properly (had to tell it to return all per view).
Appearance is fine.
