### ISSUE TITLE
[1] 3e: Add tooltips to Advanced Search fields

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#43]
When a user hovers over each field in the advanced search window, a tooltip would would appear with text offering tips for how to use the search. 

@mtedeschi to provide design
the client to provide tooltip text

**Comment by amberreeves** [comment]
@cworthen see design and annotations

https://marvelapp.com/2h8b1hj/screen/37146139

still waiting on tooltip text, so you can use placeholder text for now

**Comment by amberreeves** [comment]
@cworthen sorry about the confusion here. i see the tooltips on the search results page but not in the Advanced Search window. 

![college women open access portal 2](https://user-images.githubusercontent.com/20477677/36545319-a2a026ac-17b6-11e8-92b1-6c805499b00e.png)

**Comment by cworthen** [comment]
Hi @amberreeves ,

The tooltips are there, sometimes if don't see the changes right away, you may have to clear the cache in order for the changes to appear. To clear the cache select configuration on the top menu, then scroll down to performance (under development) and select 'clear all caches'. 

![screen shot 2018-02-22 at 6 44 36 pm](https://user-images.githubusercontent.com/16109830/36570534-83394998-1800-11e8-8647-6221eb241e52.png)

**Comment by amberreeves** [comment]
looks good

**Comment by amberreeves** [comment]
can you please add the following text to the Themes tool tip in both the advanced search pop up and on the search results page? this is text that evan drafted and she wants to see how the length of the text affects the visual design of the tool tip. 

_There are common topics that emerge across the collections represented in College Women. We call these "themes." The contributing institutions have assigned one or more themes to each item in order to provide researchers with useful examples of the kinds of materials relating to various subject areas in our collections._

**Comment by amberreeves** [comment]
looks good
