### ISSUE TITLE
[0.5] 7a: Update About page sidebar menu

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#44]
Update text in sidebar menu on the About page. 

Client to provide text. 

![about college women open access portal](https://user-images.githubusercontent.com/20477677/34015678-3cb37f2e-e0ed-11e7-8433-6fd1bb6c218b.png)

**Comment by cworthen** [comment]
Hey @amberreeves did the client provide text for the menu ?

**Comment by mtedeschi** [comment]
Yeah, you can hold on this.

**Comment by amberreeves** [comment]
i sent an email to the client asking about this, will keep you updated.

**Comment by amberreeves** [comment]
this is something that happens automatically when the client updates the header text in the WYSIWYG.
