### ISSUE TITLE
[1] 7c: Expose item identifier field on item page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#46]
On item page, expose item identifier as a field.

Example item page
https://www.collegewomen.org/node/16137

**Comment by cworthen** [comment]
Hi @amberreeves apologies, I realized I didn't add a comment and show an example of I what I added. Here's an image of the exposed identifier and where's it's located on the item pages. 
![screen shot 2018-02-22 at 6 57 10 pm](https://user-images.githubusercontent.com/16109830/36570928-5b54a92a-1802-11e8-98da-75413fe6e70c.png)

**Comment by mtedeschi** [comment]
Looks good!
