### ISSUE TITLE
[1] 7d: Add text under image to home repository

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#47]
On item page, add text below the image that says 

"You're now leaving collegewomen.org to view the item on our home repository"

and, if possible, which repository. 

If implemented: we may want to remove the “View on home repository” link further down page.

@mtedeschi to provide design

Example item page
![newport letters 1887 1899 1969 open access portal](https://user-images.githubusercontent.com/20477677/34015889-edc20952-e0ed-11e7-9c73-bb78b0f933ae.png)

**Comment by mtedeschi** [comment]
Candace: you can just follow the instructions above and add the text as provided below the image. Please remove the "View Item on Home Repository" link as requested.

**Comment by amberreeves** [comment]
this looks good to me. @mtedeschi to confirm.

https://bmc-d7-college-women.pantheonsite.io/node/16137

**Comment by mtedeschi** [comment]
This looks good.

**Comment by amberreeves** [comment]
Evan has asked that we revise this text again so that it says

Click image to leave collegewomen.org and view the item in its home repository.

**Comment by amberreeves** [comment]
looks good
