### ISSUE TITLE
[4] Sorting by format type on search results/browse page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#5]
Ability to sort up/down alphabetically by Format the way we currently can with Institution.

**Comment by jmaj** [comment]
Updated, demo can be see here, http://staging.interactivemechanics.com/7sisters/browse

**Comment by amberreeves** [comment]
that works.

**Comment by jmaj** [comment]
This is live

**Comment by amberreeves** [comment]
looks good
