### ISSUE TITLE
[4] 12: Add Transcript field to item page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#50]
On item pages, add a Transcript field. This field will link to the txt file for the item's transcript.

**Comment by cworthen** [comment]
@mike there's already a transcript field for the browse item and therefore, I can't create another field with the same machine name..should I give this field another name or delete transcript field ? Also, is the field linking to an external source for the transcript or is it opening a txt file that has the transcript ? 
![screen shot 2018-02-20 at 11 58 24 am](https://user-images.githubusercontent.com/16109830/36437733-d5a13582-1635-11e8-8348-c5bb0aa1b818.png)

**Comment by mtedeschi** [comment]
The transcript would live elsewhere, we could remove and/or repurpose. I don't think this field has data in it, yet.

**Comment by cworthen** [comment]
repurposing the transcript field

**Comment by amberreeves** [comment]
@mtedeschi can you look at this one?

**Comment by mtedeschi** [comment]
@cworthen: can you provide a link/example so we can see where its implemented?

**Comment by cworthen** [comment]
@mike sure thing, you can view the transcript here: https://bmc-d7-college-women.pantheonsite.io/node/16154

![screen shot 2018-02-20 at 11 58 24 am](https://user-images.githubusercontent.com/16109830/36520340-7a7edbd0-175e-11e8-8455-47fefb2d8069.png)

**Comment by mtedeschi** [comment]
@cworthen: I think something got lost in translation between the original issue and your question (or perhaps I misunderstood your question).

This should be a simple short text field for a URL to an external txt file. When they import their data into Drupal, it would store the link to the txt file. On the front end, it should just check for a value and conditionally show a link that says something like, "Read the transcript" that links to the external file.

**Comment by cworthen** [comment]
@mike @amberreeves this is completed, can be viewed here: https://dev-college-women.pantheonsite.io/node/15040

**Comment by mtedeschi** [comment]
Looks good as a sample.
