### ISSUE TITLE
[0.5] 6e: Add tooltips to search results page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#52]
On the search results page, add hover text (similar to item 3d on the Advanced Search window)

Client to provide text.

@mtedeschi do you know where they want these tooltips? Over the column headers (Title, Date, etc)?

**Comment by amberreeves** [comment]
@cworthen see designs and annotations 

https://marvelapp.com/2h8b1hj/screen/37146139

**Comment by amberreeves** [comment]
looks good. @cworthen can you remove the HOORAY! placeholder text before we push this live? i'm hoping the client has text ready, but if not, we can leave the tooltips blank and they can enter it whenever they have it.

**Comment by cworthen** [comment]
@amberreeves sure thing,  text removed.
