### ISSUE TITLE
[0.25] 6d: Remove the Format column from search results

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#53]
Remove the Format column from search results page **only if more space is needed after items 6b and 6c**

![browse open access portal 11](https://user-images.githubusercontent.com/20477677/34016790-3058d630-e0f1-11e7-89a2-97732b1cb7d9.png)

**Comment by cworthen** [comment]
Hey @amberreeves what is items 6b and 6c, just wanted to clarify since it says to only remove format column if more space is needed.

**Comment by amberreeves** [comment]
these are items 6b and 6c

https://github.com/InteractiveMechanics/CollegeWomen_Drupal7/issues/38

https://github.com/InteractiveMechanics/CollegeWomen_Drupal7/issues/39

@mtedeschi can you let @cworthen know whether you think we need to do this?

**Comment by cworthen** [comment]
Hey @mike would like me to go ahead and remove the format column ?

**Comment by mtedeschi** [comment]
Let's pause on this one for now.
