### ISSUE TITLE
[x] Add tool tip text

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#57]
**Advanced Search pop up window tool tip text**
Date(s)
Search for records by year or within a range of years; note that date formats are not standardized across the collections

Format
Narrow your search by format type

Institutions
Restrict your search to one or more institutions, or search across all collections

Themes
Narrow your search to items with one or more themes applied, or search across all. To learn more about themes, see 'Using the Collections'
 
**Search results page tool tip text**
Title 
Sort results alphabetically by item title

Date
Sort results alphabetically by date. Note: date formats are not standardized across the collections

Themes
Sort results alphabetically by theme, or click hyperlinked theme names to view all items in the collections with that theme applied. To learn more about themes, see 'Using the Collections'

Institution
Sort results alphabetically by institution name

Format
Sort results alphabetically by item format

**Comment by amberreeves** [comment]
looks good

**Comment by amberreeves** [comment]
Please replace the Keyword Search tooltip placeholder text with this text:

Keyword search looks for matching terms in any metadata field of the record

**Comment by cworthen** [comment]
This is completed and pushed to live

**Comment by amberreeves** [comment]
looks good
