### ISSUE TITLE
[x] Item page: Photograph images not displaying

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#59]
Most of Wellesley's and Bryn Mawr's items in the Photographs format have broken thumbnails and images on the item pages. 
Seemingly for Evan only, and only when using Chrome. Nobody else has been able to reproduce this bug. 
Letters/Correspondence and Scrapbooks formats are not affected. 
The images that _are not_ affected by this are: nodes 13960 and 13961, nodes 14505 - 14516, and 14518 - 14522.

@mtedeschi i did an advanced search for photographs from wellesley and bryn mawr and spot checked the results. i did not come across any item pages with broken images.

**Comment by mtedeschi** [comment]
@amberreeves I don't see any reason why this would be happening. I think its a non-issue or Chrome issue, perhaps? Something cached, if only appearing in Chrome on one person's computer. Going to flag as wontfix.
