### ISSUE TITLE
[0.25] “View All Themes” link text revision

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#6]
The “View All Themes” link in the home page carousel is misleading—it leads to an unfiltered browse page with all items, no view of themes. Change link text to “View all items”

**Comment by jmaj** [comment]
Updated but not live

**Comment by jmaj** [comment]
Available for QA on the dev server, https://dev-college-women.pantheonsite.io/

**Comment by amberreeves** [comment]
looks good

**Comment by jmaj** [comment]
This is on the live server
