### ISSUE TITLE
[x] Admin log in page: Add a link to reset password

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#60]
Add a link to reset password on https://www.collegewomen.org/user

**Comment by amberreeves** [comment]
@mtedeschi i don't see the reset password feature, and i see some code at the bottom of the screen. can you take a look?

![user account open access portal](https://user-images.githubusercontent.com/20477677/43904557-f167cfda-9bbc-11e8-9a1d-6f7091e12f73.png)

**Comment by mtedeschi** [comment]
Ooops, it was on staging. I confirmed and pushed live now.

**Comment by amberreeves** [comment]
evan and martha both tested this and they're not receiving the password reset emails.

**Comment by mtedeschi** [comment]
I fixed this. The SMTP module wasn't authenticating, so I disabled it and the email worked.

**Comment by amberreeves** [comment]
no word from Evan. closing this for now.
