### ISSUE TITLE
[x] Search window: Edit Search the Collections link text

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#62]
In Advanced Search window, add an 's' to the Search the Collection link text so it says Search the Collections. 

![college women open access portal 1](https://user-images.githubusercontent.com/20477677/43483212-ef0ffafe-94d8-11e8-954e-3d29d0770628.png)

**Comment by mtedeschi** [comment]
Ready for review on staging.

**Comment by amberreeves** [comment]
looks good on staging
