### ISSUE TITLE
[x] Search window: Change Format selection field from dropdown to check boxes

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#63]
In the Advanced Search dropdown menu for Format:, can we make this checkboxes? dropdown means you can only search one type at a time, people wanted to be able to combine format types in a search.

![college women open access portal 2](https://user-images.githubusercontent.com/20477677/43483294-3a9eea5c-94d9-11e8-8e17-a8d45686ee3d.png)

**Comment by mtedeschi** [comment]
This is ready for testing on the test site:
http://test-college-women.pantheonsite.io/

**Comment by mtedeschi** [comment]
I realized this may not actually make sense... none of them have more than one Format. I'm going to roll this change back so I can push other live, but we should punt this back to the client first.

**Comment by mtedeschi** [comment]
Okay, actually good to go now.

**Comment by amberreeves** [comment]
looks good on test site

**Comment by amberreeves** [comment]
can you make one adjustment? when i select more than one format filter, the formats display at the top of the search results page like this, the second one doesn't have the X out icon

![cw](https://user-images.githubusercontent.com/20477677/44747570-7c040c80-aadb-11e8-8b3d-2c2f75b727bf.png)

like this
![browse open access portal 1](https://user-images.githubusercontent.com/20477677/44747620-9ccc6200-aadb-11e8-8b7c-e88bc0a10808.png)

**Comment by amberreeves** [comment]
looks good on the test site
