### ISSUE TITLE
[x] Search results: Display all filters at top of the page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#64]
on the search results page, the filters selected display at the top, but it's only the  Institution, Theme, and Format filters that are included. Date and Keyword filters are not. 

Can we display the date and keyword filters here as well?

@mtedeschi an example below, i also entered the dates 1900-1950, and that does not show up as a filter at the top of the page with the institution, theme, and format. 

![browse open access portal](https://user-images.githubusercontent.com/20477677/43483447-ba2771e0-94d9-11e8-9c77-882cf92ce83b.png)

**Comment by mtedeschi** [comment]
Now that formats are changed, I will plan to implement this across all filters.

**Comment by amberreeves** [comment]
this looks good on the test site

![browse open access portal 2](https://user-images.githubusercontent.com/20477677/45708485-92880b80-bb4f-11e8-9a90-16d942ab4b08.png)

![browse open access portal 3](https://user-images.githubusercontent.com/20477677/45708596-de3ab500-bb4f-11e8-82ca-5c0de68a2293.png)
