### ISSUE TITLE
[x] Search results: Filters not displaying correctly at top of page

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#69]
From Evan: the Themes on the filters menu are behaving strangely; it often doesn't display all themes searched for, also there are sometimes duplicates and multiple X buttons next to one another that don't have an obvious pairing with a term

From Amber
I tested for this and could not recreate the issue. 
Here is an example of a search with three themes:
![screen shot 2018-08-13 at 9 34 32 am](https://user-images.githubusercontent.com/20477677/44034871-2fe31040-9edc-11e8-91e3-0b928ffb9a36.png)

Here is an example of a search with 4 themes:
![screen shot 2018-08-13 at 9 35 40 am](https://user-images.githubusercontent.com/20477677/44034912-449ae422-9edc-11e8-9aeb-d4215db04ccd.png)

Here s an example of a search with 6 themes: 
![screen shot 2018-08-13 at 9 36 14 am](https://user-images.githubusercontent.com/20477677/44034976-64764fc0-9edc-11e8-8385-ad27d1993b7a.png)

**Comment by mtedeschi** [comment]
I'm also not able to recreate this as described. Can we get more information and steps to recreate it from Evan?

**Comment by amberreeves** [comment]
this is being resolved with the other filter changes
