### ISSUE TITLE
[4] Add Themes menu to mobile version of site

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#7]
Currently the iOS mobile version of the Browse page only shows a search button but no Themes menu.

**Comment by jmaj** [comment]
@mtedeschi  Do you have something in mind or do you just want the hidden-sm and hidden-xs to be removed with a close icon added one?

**Comment by mtedeschi** [comment]
I could design something for this. I'll swap this task out and assign to me first to give you something to use.

**Comment by jmaj** [comment]
Available for QA on the dev server, https://dev-college-women.pantheonsite.io/node/13578

**Comment by amberreeves** [comment]
looks good

**Comment by jmaj** [comment]
Themes link and menu will show on mobile now
