### ISSUE TITLE
[x] Admin: Editing/saving an existing blog post creates a new node

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#72]
when I hit “save” on an unpublished blog post, then view, go back and edit and “save” again, it’s creating a new node each time. Is there a way to do it so that it knows to update the existing node rather than creating a new one?

**Comment by mtedeschi** [comment]
This isn't an issue.

If you create a new post, you're on: https://www.collegewomen.org/node/add/article
If you publish and then press the back button, you're not editing that page—you're creating a new one. You need to first navigate to the edit view to make adjustments.

**Comment by amberreeves** [comment]
sent to the client
