### ISSUE TITLE
[x] Edit site title that displays in browser tab

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#76]
remove the "Open Access Portal" part from the site title that displays in the browser tab, so it just says "College Women"

**Comment by amberreeves** [comment]
i'm still seeing it as 

College Women | Open Access Portal

**Comment by mtedeschi** [comment]
The title is now set to be...
Homepage = "College Women | Documenting the History of Women in Higher Education"
Other Pages = "[PAGE TITLE] | College Women"

You'll see this once it's all live since its a theme and config change.
