### ISSUE TITLE
[x] Pantheon/DNS/performance tier issue

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#77]
From Eric
Pantheon recently did a change-over of their systems, and in the process put us in a high-performance category for which they are charging nearly $500 a month, rather than the $150 we have been used to.   We can move to a lower tier, but it involves make a change to the DNS in our site.  I've pasted in the chat instructions from Pantheon below.  Is this something you can do?
Thanks!

From Pantheon
chat: Hi, looks like your site is already have Global CDN upgrade enabled, next step to do here is to point your domain to our platform by updating your DNS record to match with the required value under your domains in Domains/HTTPS tab. Do you have custom SSL cert in your site? I just asked because uploading custom cert in Global CDN is currently not available at this moment. But you can use our free Pantheon HTTPS service it is by default activated when you move to Global CDN.

Eric: I think we have the SSL cert on the site, but I'm not the person who is actively managing it. Assuming that it is there, what do we need to do next?

chat: I see, got it, you might not need your custom cert as Global CDN will be using Let's encrypt. Also, uploading custom cert is not available in Global CDN.

chat: once you're done updating your DNS record, next step is to downgrade your plan to "Performance Small".

Eric: Ok. Once we do the DNS updating, how do we downgrade the plan?

**Comment by mtedeschi** [comment]
@amberreeves Bryn Mawr College (our pal, Vince) manages the SSL certs and DNS information, so I don't believe this is something we can change. I'd suggest punting this back to him, since it seems like its out of our domain.

**Comment by amberreeves** [comment]
passed to eric/vince
