### ISSUE TITLE
[0.25] “View Original Item” link text revision

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#8]
On the item page, change the “view original item” link text to something less confusing 

Rationale: “original” suggests a dichotomy between original and facsimile in archival terms that doesn’t apply here. 

Metadata committee needs to resume discussion to come up with alternative text.

**Comment by amberreeves** [comment]
I asked Evan for the text for this link. Waiting for a response after she's back from vacation (after 6/19).

**Comment by amberreeves** [comment]
The text for the link should be 

View Item on Home Repository

**Comment by jmaj** [comment]
THis is live

**Comment by amberreeves** [comment]
example
https://www.collegewomen.org/node/13439

looks good
