### ISSUE TITLE
[2] Improved page navigation

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#9]
Add total pages to the navigation bar at the bottom of search results/browse (“<<  < 1 2 3…9 >  >>” instead of just current page and one previous/one after, “<<  < 3 4 5 >  >>”)

**Comment by jmaj** [comment]
Can I get some clarity on this.

The last page is represented by this ">>" 

So now they want it as "<< < 1 2 3…65 > >>"

Where both "65" and ">>" are the last pages ?

**Comment by amberreeves** [comment]
yes, the way you describe it here aligns with what they are asking for. do you have another suggestion or question that i should send them?

**Comment by jmaj** [comment]
No suggestion, it just seems odd is all, here's a link for QA, https://dev-college-women.pantheonsite.io/browse?subject=&institution=&start_year=&end_year=&title=&searchterm=&type=&theme_id=All&sort_by=title&sort_order=ASC&page=2

**Comment by amberreeves** [comment]
can you describe what seems odd about it?

**Comment by jmaj** [comment]
It just seems redundant, have two links that go to the last item. Seems like there's no need or use for the ">>" if they want the last page number as a link.

And I thought I added the "..." it's there now, http://staging.interactivemechanics.com/7sisters/browse

**Comment by amberreeves** [comment]
@mtedeschi can you weigh in on the best solution for this?

**Comment by mtedeschi** [comment]
It does seem redundant, but I believe they're trying to give you a sense of the number of pages in the set. What if we remove the first/last arrows and also include page 1 and page N:

<   1 ... 3 4 5 ... 50   >

**Comment by jmaj** [comment]
Updated, here, http://staging.interactivemechanics.com/7sisters/browse?subject=&institution=&start_year=&end_year=&title=&searchterm=&type=&theme_id=All&sort_by=title&sort_order=ASC&page=15

**Comment by amberreeves** [comment]
that looks good

**Comment by mtedeschi** [comment]
Great!

**Comment by jmaj** [comment]
Page navigation is on the live site
